name: 'Start PocketBase'
description: 'Downloads and starts a PocketBase server for testing'
inputs:
  version:
    description: 'PocketBase version'
    default: '0.21.2'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download and Unzip PocketBase
      shell: bash
      run: |
        curl -L -o pocketbase.zip https://github.com/pocketbase/pocketbase/releases/download/v${{ inputs.version }}/pocketbase_${{ inputs.version }}_linux_amd64.zip
        unzip -o -q pocketbase.zip
        chmod +x pocketbase

    - name: Start PocketBase
      shell: bash
      run: |
        ./pocketbase serve &

    - name: Wait for PocketBase
      shell: bash
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8090/api/collections > /dev/null; then
            echo "PocketBase is ready"
            break
          fi
          echo "Waiting for PocketBase..."
          sleep 2
        done

    - name: Create initial admin user
      shell: bash
      run: |
        curl -X POST http://localhost:8090/api/admins/records \
          -H "Content-Type: application/json" \
          -d '{"email": "groovy-api-template@fake.com", "password": "testPassword@"}'
