name: 'Start PocketBase'
description: 'Downloads and starts a PocketBase server for testing'
inputs:
  version:
    description: 'PocketBase version'
    default: '0.28.2'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download and Unzip PocketBase
      shell: bash
      run: |
        curl -L -o pocketbase.zip https://github.com/pocketbase/pocketbase/releases/download/v${{ inputs.version }}/pocketbase_${{ inputs.version }}_linux_amd64.zip
        unzip -o -q pocketbase.zip
        chmod +x pocketbase

    - name: Start PocketBase
      shell: bash
      run: |
        ./pocketbase serve &

    - name: Wait for PocketBase
      shell: bash
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8090/api/collections > /dev/null; then
            echo "PocketBase is ready"
            break
          fi
          echo "Waiting for PocketBase..."
          sleep 2
        done

    - name: Create PocketBase admin (superuser)
      shell: bash
      run: ./pocketbase superuser create admin@fake.com adminPassword

    - name: Authenticate as PocketBase admin
      id: admin-auth
      shell: bash
      run: |
        ADMIN_JSON=$(curl -s -X POST http://localhost:8090/api/admins/auth-with-password \
          -H "Content-Type: application/json" \
          -d '{"email":"admin@fake.com","password":"adminPassword"}')
        echo "ADMIN_JSON: $ADMIN_JSON"
        echo "token=$(echo $ADMIN_JSON | jq -r '.token')" >> $GITHUB_OUTPUT

    - name: Create test user
      id: create-user
      shell: bash
      run: |
        CREATE_USER_JSON=$(curl -s -X POST http://localhost:8090/api/collections/users/records \
          -H "Authorization: Bearer ${{ steps.admin-auth.outputs.token }}" \
          -H "Content-Type: application/json" \
          -d '{
                "email": "groovy-api-template@fake.com",
                "password": "testPassword@",
                "passwordConfirm": "testPassword@"
              }')
        echo "CREATE_USER_JSON: $CREATE_USER_JSON"
        echo "id=$(echo $CREATE_USER_JSON | jq -r '.id')" >> $GITHUB_OUTPUT

    - name: Mark test user as verified
      shell: bash
      run: |
        curl -X PATCH http://localhost:8090/api/collections/users/records/${{ steps.create-user.outputs.id }} \
          -H "Authorization: Bearer ${{ steps.admin-auth.outputs.token }}" \
          -H "Content-Type: application/json" \
          -d '{"verified": true}'
