name: CI and CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-and-cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'groovy-api-template'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Start PocketBase
        uses: ./.github/actions/pocketbase

      - name: Build with Gradle
        run: ./gradlew clean build -Denvironment=ci

      - name: Upload Spock Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-test-report
          path: build/reports/tests/test

      - name: Set git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Tag new version
        run: |
          ./gradlew currentVersion
          ./gradlew release -Prelease.scope=patch

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Staging with Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy -a $APP_NAME

      - name: Test Staging
        run: ./gradlew test -Denvironment=staging --tests '*FT'

      - name: Upload Spock Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: staging-test-report
          path: build/reports/tests/test