name: CI and CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-and-cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'groovy-api-template'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set PocketBase Version
        run: echo "PB_VERSION=0.21.2" >> $GITHUB_ENV

      - name: Download and Unzip PocketBase
        run: |
          curl -L -o pocketbase.zip https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip
          unzip -o -q pocketbase.zip
          chmod +x pocketbase

      - name: Start PocketBase
        run: |
          ./pocketbase serve &

      - name: Wait for PocketBase
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8090/api/collections > /dev/null; then
              echo "PocketBase is ready"
              break
            fi
            echo "Waiting for PocketBase..."
            sleep 2
          done

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Staging with Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy -a $APP_NAME

      - name: Test Staging
        run: ./gradlew test -Denvironment=staging --tests '*FT'