name: CI and CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-and-cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'groovy-api-template'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'azul'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build -Denvironment=ci

      - name: Set git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Staging with Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy -a $APP_NAME