name: Dependency Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.git_status.outputs.changes_detected }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Update Dependencies
        id: update_deps
        run: ./gradlew useLatestVersions

      - name: Check for Changes
        id: git_status
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

  build-and-merge:
    runs-on: ubuntu-latest
    needs: update-dependencies
    if: needs.update-dependencies.outputs.changes_detected == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Run Tests
        run: |
          ./gradlew clean build

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update dependencies to latest stable versions"
          git push origin HEAD:dependency-update

      - name: Merge to Main
        run: |
          git fetch origin main
          git checkout main
          git merge --ff-only dependency-update
          git push origin main
