name: Dependency Update

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Update Dependencies
        run: ./gradlew useLatestVersions

      - name: Start PocketBase
        uses: ./.github/actions/pocketbase

      - name: Build and Test
        run: ./gradlew clean build -Denvironment=ci

      - name: Commit and Push Changes (if any)
        id: git_status
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes detected."
          else
            git commit -m "chore: update dependencies to latest stable versions"
            git push origin main
            echo "Pushed changes to main."
          fi